using System.Collections;
using System.Collections.Generic;
using System;
using System.IO;
using System.Linq;
using UnityEngine;

public class FileManager : MonoBehaviour
{
    public string SongsDirString = System.IO.Path.Combine(Application.streamingAssetsPath, "Songs");

    DirectoryInfo SongsDir;

    // TESTING
    public SerializableSheet te;
    public SerializableInfo st;

    private void Start()
    {
        Debug.Log(SongsDirString);

        SongsDir = new DirectoryInfo(SongsDirString);

        try
        {
            if (!SongsDir.Exists)
            {
                Debug.Log("No Songs folder detected. Auto-generated by system.");
                SongsDir.Create();
            }
            else
                Debug.Log("Songs folder found.");

            var sheetDir = 
            from item in SongsDir.EnumerateDirectories() 
            where Directory.GetFiles(item.FullName, "*.mrs").Count() != 0 
            select item;
            
            foreach (var item in sheetDir)
            {
                Debug.Log(item.Name);
            }

        }
        catch (Exception e)
        {
            Debug.LogError("Error Occured. : " + e);
            throw;
        }

        Debug.Log(JsonUtility.ToJson(te));
        Debug.Log(JsonUtility.ToJson(st));
    }

    private void Update()
    {
        
    }
}
